### PR TITLE
Convert to Java

### PR DESCRIPTION
**Pull request by imachadoglobant**
This is a conversion from the Kotlin implementation back to Java as requested by the Google Orion Wi-Fi team as part of their partnership with Globant.

@stephen-soltesz: Could you please review?
CC: @sywang-desiree

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Hello, @imachadoglobant -- Thank you! I've added a few comments.

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-:-MurIfiC4XPjjUzS1lAf:bt1fu6a)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @imachadoglobant)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJLO7Ch27zrkQE1Yd:-MurJLO8-qTkqLFawxHU:b-1ghvnz) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L1)):*
> ```Markdown
> # ndt7-java
> ```

If you use VSCode, I can recommend markdownlint -- https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

If you don't have access to a simple markdownlinter, please do a once over on this doc to wrap at 80cols and eliminate EOL spaces.
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurPIXODq_KLTU0Skaq:-MurPIXODq_KLTU0Skar:bjd5bwx) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L3)):*
> ```Markdown
> # ndt7-java
> 
> Java implementation of the [NDT7 protocol by M-Lab](https://github.com/m-lab/ndt-server/blob/master/spec/ndt7-protocol.md)
> ```

Please add a note that this implementation is "community supported".
___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-MurJosk0VCXiHbpFNXp:bxoqz6p) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
> ```Markdown
> # How it works
> 
> Consumers wishing to use the NDT7 speed test should create a subclass of type `NDTTest` and override the functions that it exposes
> ```

Are there helpful build instructions available? If I'd like to run this for development, what steps would I take?

Can you give a short summary of how to run the unit tests for this package?
___
*[libndt7/src/main/java/net/measurementlab/ndt7/android/NdtTest.java, line 42 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurKAbR1pnrNJzqd7bq:-MurKAbR1pnrNJzqd7br:b7ffppm) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/libndt7/src/main/java/net/measurementlab/ndt7/android/NdtTest.java#L42)):*
> ```Java
> 
>     public static final String MEASUREMENT_SERVER_URL =
>             "https://locate.measurementlab.net/v2/nearest/ndt/ndt7?client_name=ndt7-android&client_version=%s";
> ```

Thank you for preserving the client_name and client_version parameters. Since this is a new implementation, please update the client_name to reference this implementation, perhaps: `client_name=ndt7-android-java`.

**Comment by imachadoglobant** [comment]
Hi @stephen-soltesz, thank you for your comments. I have addressed them all and I have also added the versionCode and versionName that were missing. I made them match the version of the library in Kotlin. Do you think we should mention this is just a migration from that code? Could you please recheck my PR? Thanks in advance!

CC: @sywang-desiree

**Review by imachadoglobant — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJLO7Ch27zrkQE1Yd:-Muw-EoNEiwy9YpLcWyA:b-896fix) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If you use VSCode, I can recommend markdownlint -- https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

If you don't have access to a simple markdownlinter, please do a once over on this doc to wrap at 80cols and eliminate EOL spaces.
</blockquote></details>

Done.
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurPIXODq_KLTU0Skaq:-Muw-G8i4UsOaXHTRB_A:b-896fix) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L3)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a note that this implementation is "community supported".
</blockquote></details>

Done.
___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-Muw-GxJ1m762CXv6sG2:b-896fix) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are there helpful build instructions available? If I'd like to run this for development, what steps would I take?

Can you give a short summary of how to run the unit tests for this package?
</blockquote></details>

Done.
___
*[libndt7/src/main/java/net/measurementlab/ndt7/android/NdtTest.java, line 42 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurKAbR1pnrNJzqd7bq:-Muw-Hz1BA90NEdjxDKq:b-896fix) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/libndt7/src/main/java/net/measurementlab/ndt7/android/NdtTest.java#L42)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for preserving the client_name and client_version parameters. Since this is a new implementation, please update the client_name to reference this implementation, perhaps: `client_name=ndt7-android-java`.
</blockquote></details>

Done.

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-Muw7_8l0KmsiwRuRQbC:b-y73lc9) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
<details><summary><i>Previously, imachadoglobant (Ismael Machado) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you. So that we can integrate the unit tests in to a CI system, we need an environment setup with a suitable version of gradle and the android sdk.

Ideally, this would be in a Dockerfile that we build, and then from which we run the unit tests.

I've found official gradle docker images and some candidate android-sdk images (not official) -- but you're more familiar with the toolchain. Can you recommend a docker environment or Dockerfile to create an environment for running the unit tests?
___
*[libndt7/src/main/java/net/measurementlab/ndt7/android/NdtTest.java, line 42 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurKAbR1pnrNJzqd7bq:-Muw3I_MAypKD60NhxL2:b-9755fa) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/libndt7/src/main/java/net/measurementlab/ndt7/android/NdtTest.java#L42)):*
<details><summary><i>Previously, imachadoglobant (Ismael Machado) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you.

**Review by imachadoglobant — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-Mv0Ppd604vXw4oGy4NF:b3e2ad) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you. So that we can integrate the unit tests in to a CI system, we need an environment setup with a suitable version of gradle and the android sdk.

Ideally, this would be in a Dockerfile that we build, and then from which we run the unit tests.

I've found official gradle docker images and some candidate android-sdk images (not official) -- but you're more familiar with the toolchain. Can you recommend a docker environment or Dockerfile to create an environment for running the unit tests?
</blockquote></details>

No problem! You are right, we can use this Docker image: https://hub.docker.com/r/androidsdk/android-30

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-Mv4Iiac8Ovu44cpDZZJ:b-693rh8) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
That's very helpful. When I create a docker image based on androidsdk/android-30 and attempt to run the unit tests, I receive the error below. What steps are missing? Are you able to run the tests to completion in this docker image?

```
FROM androidsdk/android-30
COPY --chown=gradle:gradle . /home/gradle/src/ndt7-client-android-java
WORKDIR /home/gradle/src/ndt7-client-android-java
```

```
$ docker build -t local-build .
$ docker run -it local-build ./gradlew connectedAndroidTest
...
> Task :libndt7:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libndt7:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 12s
```

**Review by imachadoglobant — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-Mv4jMG22XLeFecLotsX:bhrl4v2) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

That's very helpful. When I create a docker image based on androidsdk/android-30 and attempt to run the unit tests, I receive the error below. What steps are missing? Are you able to run the tests to completion in this docker image?

```
FROM androidsdk/android-30
COPY --chown=gradle:gradle . /home/gradle/src/ndt7-client-android-java
WORKDIR /home/gradle/src/ndt7-client-android-java
```

```
$ docker build -t local-build .
$ docker run -it local-build ./gradlew connectedAndroidTest
...
> Task :libndt7:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libndt7:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 12s
```
</blockquote></details>

Instrumented tests require a running emulator, maybe you're missing configuring and running an emulator for the tests to run on. The Docker image readme file mentions that you can install and start an emulator with these commands:
```
avdmanager create avd -n first_avd --abi google_apis/x86_64 -k "system-images;android-30;google_apis;x86_64"
emulator -avd first_avd -no-window -no-audio
```

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-MvJkqUS7lgfXgK0E5i3:b9ga8fx) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
Great -- though I get a similar error now too unfortunately. Can you help?

Update to Dockerfile to include the emulator.
```
FROM androidsdk/android-30                                                      
COPY --chown=gradle:gradle . /home/gradle/src/ndt7-client-android-java          
WORKDIR /home/gradle/src/ndt7-client-android-java                               
RUN echo no | avdmanager create avd -n first_avd --abi google_apis/x86_64 -k "system-images;android-30;google_apis;x86_64"
```

Run the new test in the new image by starting the emulator first.
```
$ docker run -it local-build bash -c 'emulator -avd first_avd -no-window -no-audio & ./gradlew connectedAndroidTest'
emulator: Android emulator version 30.7.5.0 (build_id 7491168) (CL:N/A)
Downloading https://services.gradle.org/distributions/gradle-7.2-bin.zip
handleCpuAcceleration: feature check for hvf
emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.

.............................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-7.2-bin/2dnblmf4td7x66yl1d74lt32g/gradle-7.2-bin.zip to /root/.gradle/wrapper/dists/gradle-7.2-bin/2dnblmf4td7x66yl1d74lt32g
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-7.2-bin/2dnblmf4td7x66yl1d74lt32g/gradle-7.2/bin/gradle

Welcome to Gradle 7.2!

Here are the highlights of this release:
 - Toolchain support for Scala
 - More cache hits when Java source files have platform-specific line endings
 - More resilient remote HTTP build cache behavior

For more details see https://docs.gradle.org/7.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Checking the license for package Android SDK Build-Tools 30.0.3 in /opt/android-sdk-linux/licenses
License for package Android SDK Build-Tools 30.0.3 accepted.
Preparing "Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)".
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" ready.
Installing Android SDK Build-Tools 30.0.3 in /opt/android-sdk-linux/build-tools/30.0.3
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
Checking the license for package Android SDK Platform 31 in /opt/android-sdk-linux/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision: 1)".
"Install Android SDK Platform 31 (revision: 1)" ready.
Installing Android SDK Platform 31 in /opt/android-sdk-linux/platforms/android-31
"Install Android SDK Platform 31 (revision: 1)" complete.
"Install Android SDK Platform 31 (revision: 1)" finished.
[adb]: * daemon not running; starting now at tcp:5037
[adb]: * daemon started successfully
> Task :libndt7:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libndt7:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!
```

You're much more familiar with this toolchain. Any help you can provide would be welcome. Thank you!

**Comment by stephen-soltesz** [comment]
@imachadoglobant are you able to help?

**Review by imachadoglobant — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-MwlYXks8-3HFUFY_AcZ:b-965xbv) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
Since I haven't worked with Docker before, I have been doing some research and local testing. 

According to Android official docs: 
> "You can't run a VM-accelerated emulator inside another VM". 
Actually, it depends on what machine you are running Docker and if it has hardware acceleration tools installed.

However, it is possible to run an older emulator that doesn't require graphic acceleration on Docker. I found these articles that explain how you can do that:
- https://github.com/mingchen/docker-android-build-box
- https://andresand.medium.com/android-emulator-on-docker-container-f20c49b129ef
- https://github.com/thyrlian/AndroidSDK#emulator

I tried with several setups, but this is the only one that worked:
1. Pull and start this Docker image: https://hub.docker.com/r/thyrlian/android-sdk/dockerfile
2. Install Android 24 SDK (later versions use arm64): `sdkmanager "platform-tools" "platforms;android-24" "emulator"`
3. Install Android 24 image for ARM ABI v7a `sdkmanager "system-images;android-24;default;armeabi-v7a"`
4. Register emulated device: `echo no | avdmanager create avd -n first_avd -k "system-images;android-24;default;armeabi-v7a"`
5. Start ADB server: `adb start-server`
6. Start emulator: `emulator -avd first_avd -no-audio -no-boot-anim -gpu off`
7. Wait for the emulator to start

**Review by imachadoglobant — COMMENTED** [review]
Sorry, I was OOO for a couple of weeks.

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-:-Mwlc7Uj-0he8PCEDmyc:b-4c6v6v)* status: 1 change requests, 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MurJosk0VCXiHbpFNXo:-Mxg28N40CVJQ_-UKgkR:bwe265j) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/f58a6d7c5a5371895824e6283565f0be4e9d6531/README.md#L8)):*
<details><summary><i>Previously, imachadoglobant (Ismael Machado) wrote…</i></summary><blockquote>

Since I haven't worked with Docker before, I have been doing some research and local testing. 

According to Android official docs: 
> "You can't run a VM-accelerated emulator inside another VM". 
Actually, it depends on what machine you are running Docker and if it has hardware acceleration tools installed.

However, it is possible to run an older emulator that doesn't require graphic acceleration on Docker. I found these articles that explain how you can do that:
- https://github.com/mingchen/docker-android-build-box
- https://andresand.medium.com/android-emulator-on-docker-container-f20c49b129ef
- https://github.com/thyrlian/AndroidSDK#emulator

I tried with several setups, but this is the only one that worked:
1. Pull and start this Docker image: https://hub.docker.com/r/thyrlian/android-sdk/dockerfile
2. Install Android 24 SDK (later versions use arm64): `sdkmanager "platform-tools" "platforms;android-24" "emulator"`
3. Install Android 24 image for ARM ABI v7a `sdkmanager "system-images;android-24;default;armeabi-v7a"`
4. Register emulated device: `echo no | avdmanager create avd -n first_avd -k "system-images;android-24;default;armeabi-v7a"`
5. Start ADB server: `adb start-server`
6. Start emulator: `emulator -avd first_avd -no-audio -no-boot-anim -gpu off`
7. Wait for the emulator to start




</blockquote></details>

Okay, I think we're getting closer. Using the following in a Dockerfile:

```
FROM thyrlian/android-sdk:7.2
COPY --chown=gradle:gradle . /home/gradle/src/ndt7-client-android-java
WORKDIR /home/gradle/src/ndt7-client-android-java
RUN apt-get install -y libpulse0:i386 libpulse0 libxcomposite1 libxcursor1 libxdamage1
RUN sdkmanager "platform-tools" "platforms;android-24" "emulator"
RUN sdkmanager "system-images;android-24;default;armeabi-v7a"
RUN echo no | avdmanager create avd -n first_avd -k "system-images;android-24;default;armeabi-v7a"
```

I can build & run a local testing image, with the emulators to run the tests:

```
docker build -t local-android .
docker run -it local-android bash -c "adb start-server & sleep 5 ; emulator -avd first_avd -no-audio -no-boot-anim -gpu off -no-window & sleep 5; ./gradlew connectedAndroidTest --info"
```

And the testing gets further than it has before now, but reports "Total tests 5, failure 1, passed 4,"

```
Starting 5 tests on first_avd(AVD) - 7.0

net.measurementlab.ndt7.androidTest.Ndt7HealthTest > testNetworkCallableCanContinueSpeedTestDespiteError[first_avd(AVD) - 7.0] SUCCESS 

net.measurementlab.ndt7.androidTest.Ndt7HealthTest > testNetworkCallableCanPerformNdt7SpeedTest[first_avd(AVD) - 7.0] FAILED 
        java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)

net.measurementlab.ndt7.androidTest.PayloadTransformerTest > testDynamicTuningWillDouble[first_avd(AVD) - 7.0] SUCCESS 

net.measurementlab.ndt7.androidTest.PayloadTransformerTest > testDynamicTuningDoesNotChangeIfQueueIsSaturated[first_avd(AVD) - 7.0] SUCCESS 

net.measurementlab.ndt7.androidTest.PayloadTransformerTest > testDynamicTuningDoesNotChangeIfMaxSize[first_avd(AVD) - 7.0] SUCCESS 
Tests on first_avd(AVD) - 7.0 failed: There was 1 failure(s).

[XmlResultReporter]: XML test result file generated at /home/gradle/src/ndt7-client-android-java/libndt7/build/outputs/androidTest-results/connected/TEST-first_avd(AVD) - 7.0-libndt7-.xml. Total tests 5, failure 1, passed 4, 
```

Are you able to reproduce these steps?

Do you know what may be wrong with `testNetworkCallableCanPerformNdt7SpeedTest[first_avd(AVD)`?

Thank you.

**Comment by stephen-soltesz** [comment]
if it's helpful to schedule a time to work through this, please let me know @imachadoglobant .

**Review by stephen-soltesz — COMMENTED** [review]
The build / test can pass successfully (which is great), however it is not consistent (less great). The successes take <10min. The failures report an error like the one below. This is using the same commands.

While running the tests gradlew seems to download a ton of dependencies including "Install Android SDK Platform" 26.1.1, 30.0.3, 31. Since the emulator is version 24, I'm confused by this but suspect the variable delays from those downloads may be part of the variation in results.

When I run `gradlew` without the test, it does something initially, and the tests have an easier time succeeding after, but still seem to download more than expected, and still sometimes fail.

Do you know - is there more setup that can be done before running the tests?

```
$ docker run -it local-android bash -c \
    "adb start-server & sleep 15 ; \
     emulator -avd first_avd -no-audio -no-boot-anim -gpu off -no-window & sleep 90; \
    ./gradlew ; sleep 10; \
    ./gradlew connectedAndroidTest"
```

```
[PropertyFetcher]: ShellCommandUnresponsiveException getting properties for device emulator-5554
java.lang.Throwable: ShellCommandUnresponsiveException getting properties for device emulator-5554
        at com.android.ddmlib.PropertyFetcher.handleException(PropertyFetcher.java:248)
        at com.android.ddmlib.PropertyFetcher.access$500(PropertyFetcher.java:30)
        at com.android.ddmlib.PropertyFetcher$1.run(PropertyFetcher.java:211)
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:689)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:468)
        at com.android.ddmlib.internal.DeviceImpl.executeShellCommand(DeviceImpl.java:705)
        at com.android.ddmlib.PropertyFetcher$1.run(PropertyFetcher.java:207)

[PropertyFetcher]: ShellCommandUnresponsiveException getting properties for device emulator-5554
java.lang.Throwable: ShellCommandUnresponsiveException getting properties for device emulator-5554
        at com.android.ddmlib.PropertyFetcher.handleException(PropertyFetcher.java:248)
        at com.android.ddmlib.PropertyFetcher.access$500(PropertyFetcher.java:30)
        at com.android.ddmlib.PropertyFetcher$1.run(PropertyFetcher.java:211)
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:689)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:468)
        at com.android.ddmlib.internal.DeviceImpl.executeShellCommand(DeviceImpl.java:705)
        at com.android.ddmlib.PropertyFetcher$1.run(PropertyFetcher.java:207)


> Task :libndt7:connectedDebugAndroidTest
Skipping device 'first_avd(AVD)' for 'libndt7:': Unknown API Level

 > : No compatible devices connected.[TestRunner] FAILED 
Found 1 connected device(s), 0 of which were compatible.

> Task :libndt7:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libndt7:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/gradle/src/ndt7-client-android-java/libndt7/build/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
93 actionable tasks: 93 executed
``` 

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-:-MyPtgKCBpiJqPGzwSRy:bgmp1g6)* status: 1 change requests, 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
When I use `./gradlew build` as an intermediate step, I have a very good success rate - Is this the correct step to use? Is this considered "best practice?"

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-:-MyS0H687dEvR7tUIfYp:bxn7esf)* status: 1 change requests, 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
@imachadoglobant Please add a Dockerfile that includes the following:

```
FROM thyrlian/android-sdk:7.2
COPY . /home/gradle/src/ndt7-client-android-java
WORKDIR /home/gradle/src/ndt7-client-android-java
RUN apt-get install -y libpulse0:i386 libpulse0 libxcomposite1 libxcursor1 libxdamage1
RUN sdkmanager "platform-tools" "platforms;android-24" "emulator"
RUN sdkmanager "system-images;android-24;default;armeabi-v7a"
RUN echo no | avdmanager create avd -n first_avd -k "system-images;android-24;default;armeabi-v7a"
```

And add the following steps to the README for running the tests:

```
docker build -t local-android .
docker run --rm  -it local-android bash -c     "adb start-server & sleep 15 ; \
     emulator -avd first_avd -no-audio -no-boot-anim -gpu off -no-window & sleep 90; \
    ./gradlew build; sleep 10; \
    ./gradlew connectedAndroidTest"
```

Or any other equivalent sequence that you believe will be recognized by Android developers as best practices.

With this, I think this will be sufficient to add CI.

> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-:-MyUYG-_2flIYCW6cIrm:bxk8c1o)* status: 1 change requests, 0 of 1 approvals obtained

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @imachadoglobant)

___
*[README.md, line 24 at r4](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MysRI7yCOk0-WTt4XtM:-MysRI7yCOk0-WTt4XtN:bqetmua) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/bb22285fe107472aa97405c3892834721cc5b08f/README.md#L24)):*
> ```Markdown
> ```
> docker build -t local-android .
> docker run --rm  -it local-android bash -c "adb start-server & sleep 15 ; \
> ```

@imachadoglobant  Can you confirm that someone familiar with android development would look at these steps and recognize them as correct?

**Review by stephen-soltesz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[README.md, line 24 at r4](https://reviewable.io/reviews/m-lab/ndt7-client-android-java/1#-MysRI7yCOk0-WTt4XtM:-Mz1biqZ3peGWjK8ABrh:bjz54m0) ([raw file](https://github.com/m-lab/ndt7-client-android-java/blob/bb22285fe107472aa97405c3892834721cc5b08f/README.md#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

@imachadoglobant  Can you confirm that someone familiar with android development would look at these steps and recognize them as correct?
</blockquote></details>

Confirmed over email.

**Pull request merged**
